[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sylvan_new = "2ZruFMPznDSMcTry1X4JemNDrA284jiy7mjWV7LW77Aw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/serafim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
